#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from axion_test --no-log-prefix | grep axion_test && docker-compose -f docker-compose.test.yml down --volumes
npx lint-staged
